set(INFO_DYNAMITE_LIBRARY_DIR "${CMAKE_SOURCE_DIR}/libs")

set(SPROUT_INCLUDE_DIR "${INFO_DYNAMITE_LIBRARY_DIR}/sprout/")
set(LIBNM_INCLUDE_DIR "${INFO_DYNAMITE_LIBRARY_DIR}/libnm/include/")
set(LIBLUCENT_INCLUDE_DIR "${INFO_DYNAMITE_LIBRARY_DIR}/liblucent/include/")
